### ISSUE TITLE
Can't blink with pretrained model

### ISSUE THREAD

**Issue by kendo6666** [Doubiiu/CodeTalker#31]
We use the pre-trained model to test on the vocaset dataset, but all the rendered videos cannot blink. How should we solve it?

**Comment by Doubiiu** [comment]
Hi, since the 4D face scans in VOCA and BIWI datasets don't contain blink motions, the model trained on them cannot produce facial animations with blink. You may need construct a new dataset (3d face reconstruction) or find a new dataset and train the model on it to generate facial animations with blink.

**Comment by kendo6666** [comment]
@Doubiiu Thanks, I'll try, but it's not easy to find such a dataset
